name: skipthoughts
data-path: /home/user/datasets/book-corpus
vocab-path: ../vocab/book-corpus-30000.pkl
save-dir: ./
gpus: [0, 1, 2, 3]
previews: 10
wordembed-type: glove
wordembed-path: /home/user/datasets/glove/glove.840B.300d.txt
fasttext-path: null
wordembed-freeze: false
epochs: 10
batch-size: 256
omit-prob: 0.05
swap-prob: 0.05
val-period: 100
save-period: 1000
max-len: 30
visdom-host: localhost
visdom-port: 8097
visdom-buffer-size: 10
encoder-cell: lstm
decoder-cell: gru
before: 1
after: 1
predict-self: false
word-dim: 300
hidden-dim: 2400
layers: 1
bidirectional: true
dropout-prob: 0.05